### ISSUE TITLE
Create query string URL to "remember" characters

### ISSUE THREAD

**Issue by evangipson** [evangipson/faterator#3]
This is so people can share their characters!

**Comment by robertpateii** [comment]
heh this means you need to tag every aspect/stunt/job/thing with an id which will immediately make things interesting. quickest easiest step may be to move the copy into json file(s) and then get them and parse them into JavaScript objects or make a small little api to do it for you and you just api.getRandomJob() and you get {name:sailor; id: slr}.

i came here to suggest you should break out the data stuff anyway into files that are easily edited by non-javascript developers (for which JSON qualifies... sure they may be break it but you test that before you merge).

**Comment by evangipson** [comment]
Oh man, I'd love to break out the arrays into JSON objects for easy editing by non-javascript devs. Great idea! I'll probably make a separate issue for that.  Nevermind - I see you already did that!

I need to turn every aspect/job/etc. into an object with a unique ID.

**Comment by robertpateii** [comment]
other ideas we talked about: do a short-case-sensitive guid like tiny URLs and slap that in the fragment since the fragments will be case sensitive to your javascript code. assign each aspect its own guid and yay

so example:
{name: "sailor", guid, "whatever-comes-from-your-short-guid-generator-that-you-steal-from-a-tiny-url-serivce-that's-open-source"}

then that guid goes in the fragement

and you parse the fragment to figure out what's in the character sheet. (or query strings)

parsing will be interesting but i can already think of a few ways to approach that so it's do-able.

**Comment by robertpateii** [comment]
another idea would be to use short names provided by a human as IDs. presumably you'd be grouping them into categories anyway like job, aspect, trouble so the shorrt names need only be unique within their group. and then you get the bonus of having a human readable URL that clues you into the character.

**Comment by evangipson** [comment]
Been doing tons of work on this in https://github.com/evangipson/faterator/pull/8

Now names and high aspect jobs both work via url!

**Comment by evangipson** [comment]
Done as of testing today! https://github.com/evangipson/faterator/pull/8

Approaches still aren't part of the query string, but I sort of like them being random every time.
